//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_INFO
    {
        public string item_name { get; set; }
        public int list_id { get; set; }
        public string item_desc { get; set; }
        public Nullable<System.DateTime> item_deadline { get; set; }
        public System.DateTime creation_date { get; set; }
        public string item_status { get; set; }
    
        public virtual LIST_INFO LIST_INFO { get; set; }
    }
}
